import Image from "next/image";
import "./globals.css";
import Script from "next/script";
import { envSchema } from "@/types/env";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // We set a default parser here

  let env = envSchema.safeParse(process.env);

  if (!env.success) {
    throw new Error("Invalid Environment Variable config");
  }
  return (
    <html lang="en">
      <head>
        <Script
          src={"https://www.googletagmanager.com/gtag/js?id=G-MM8QMY5JWN"}
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
        window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', '${process.env.GOOGLE_TAG_ID}');
        `}
        </Script>
      </head>

      <body className="mx-auto flex min-h-screen max-w-2xl flex-col">
        <header className="container">
          <div className="flex items-center justify-between border-b py-4">
            <a
              href="https://twitter.com/ivanleomk"
              target="_blank"
              rel="noreferrer"
              className="flex items-center space-x-2"
            >
              <div className="block h-10 w-10 overflow-hidden rounded-full">
                <Image
                  src="/ProfilePic.jpeg"
                  alt="Logo"
                  width={48}
                  height={48}
                />
              </div>
              <div className="flex flex-col space-y-1 text-sm leading-none">
                <p className="font-bold">@ivanleomk</p>
                <span>I write code sometimes</span>
              </div>
            </a>
            <div className="flex items-center space-x-4 cursor-pointer ">
              <div className="text-sm hover:font-semibold">Posts</div>
              <div className="text-sm hover:font-semibold">Work Log</div>
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
