import Image from "next/image";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="mx-auto flex min-h-screen max-w-2xl flex-col">
        <header className="container">
          <div className="flex items-center justify-between border-b py-4">
            <a
              href="https://twitter.com/ivanleomk"
              target="_blank"
              rel="noreferrer"
              className="flex items-center space-x-2"
            >
              <div className="block h-10 w-10 overflow-hidden rounded-full">
                <Image
                  src="/ProfilePic.jpeg"
                  alt="Logo"
                  width={48}
                  height={48}
                />
              </div>
              <div className="flex flex-col space-y-1 text-sm leading-none">
                <p className="font-bold">@ivanleomk</p>
                <span>I write code sometimes</span>
              </div>
            </a>
            <div className="flex items-center space-x-4 cursor-pointer ">
              <div className="text-sm hover:font-semibold">Posts</div>
              <div className="text-sm hover:font-semibold">Work Log</div>
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
